### PR TITLE
Add remaining known demographic schemes

### PR DESCRIPTION
**Pull request by as2388**

### CODE REVIEW

**Comment by ParthaMoman** [comment]
this looks good, as much as I can tell by eye, can I check:
1. Where does tha mapping happen between different geographical hierarchies, that's pretty key to review as well
2. Does it make sense to use age categorically? I can imagine we might ask other numeric questions with even larger ranges, and it looks tedious to have to verify what is an obvious sequence. Any alternative?

**Comment by as2388** [comment]
@ParthaMoman 
1. This is handled automatically, using maps defined here in Core: https://github.com/AfricasVoices/CoreDataModules/blob/f28603030cf928266092cf0221044116e69e7c1f/core_data_modules/cleaners/codes/somalia_codes.py#L175

2. Not for ReDSS (cc @lukechurch)

**Comment by ParthaMoman** [comment]
okay - looked through high-level hierachies and looks good to me!

**Review by lukechurch — APPROVED** [review]

**Comment by as2388** [comment]
@ParthaMoman thanks for reviewing. If you're happy with a PR, please use the Review Changes -> Approve button in future

**Review by ParthaMoman — APPROVED** [review]

**Comment by ParthaMoman** [comment]
sorry for gitfail!

**Pull request merged**
