### PR TITLE
Synchronise Control Codes between Binaries/Reasons

### PR DESCRIPTION
**Pull request by as2388**
Review #51 first

### CODE REVIEW

**Comment by lukechurch** [comment]
@as2388 I'd like to review after #51 has been up merged please

**Comment by as2388** [comment]
@lukechurch ready for review now

**Review by lukechurch — APPROVED** [review]
I think this would need tests if it were to go into core, its a fairly complicated piece of logic, but ok for now in project

**Comment by as2388** [comment]
This PR changes the output of the pipeline compared to the file used in analysis. Given that, and that this code was incorporated into https://github.com/AfricasVoices/Project-ADSS exactly as proposed here, I'm closing this PR without merging. See Project-ADSS instead.

**Pull request closed without merging**
