### PR TITLE
Add Operator Scheme

### PR DESCRIPTION
**Pull request by as2388**
Wondering if some of the control codes make any sense here. Leaving them in unless instructed otherwise.

### CODE REVIEW

**Comment by ParthaMoman** [comment]
this makes sense, though if possible, I'd like to review the operator codes, as there is a new MNO. In terms of controls, I usually see two things happen. One is that someone participates by another channel - NA, or that someone has a phone by an unrecognised operator (in Somalia it happens!) -ie. NC or "operator unknown". I cannot think how the rest would be relevant!

**Comment by as2388** [comment]
@ParthaMoman removed all the control codes but NA and NC. Approximately when do you expect to find out about the new operator?

**Comment by ParthaMoman** [comment]
Great - +25268 : Somnet

**Review by lukechurch — APPROVED** [review]

**Comment by as2388** [comment]
@ParthaMoman: added a code for Somnet. Please approve this if the scheme looks good now.

**Review by ParthaMoman — APPROVED** [review]

**Pull request merged**
