### PR TITLE
Add gender scheme

### PR DESCRIPTION
**Pull request by as2388**

### CODE REVIEW

**Comment by ParthaMoman** [comment]
What is outputted into final dataset for analysis - is it Display Text? in which case I'd prefer to have the () and whatevers inside of them removed

**Comment by ParthaMoman** [comment]
additionally can we keep NL - non-logical as a standard code?

**Comment by lukechurch** [comment]
> additionally can we keep NL - non-logical as a standard code?

@ParthaMoman can I understand a little more about what you want to use it for?

We've not seen NL being used in any of the pipelines in the past, and it's pretty ambiguous about what it is that wasn't logical and why. So I'd prefer to understand a bit about what you're using it for and give you codes for that.

**Comment by as2388** [comment]
@ParthaMoman there will be a new field in each code for the string which will be output to the final dataset. This won't be ready until next week, but at least you'll be able to code in Coda using the scheme seen here.

**Comment by ParthaMoman** [comment]
@as2388 thanks, that makes sense

@lukechurch so it only comes in when we use split patterns for asking questions. I THINK it's just a fluke that this hasn't come up. But we often had a problem that for example we'd ask someone if they lived in an urban or rural areas, and then we'd only ask those in rural areas whether they were nomads (assumption = all nomads are rural dwellers) but because the split is not perfect in rapidpro (based on minimal regexs), it was quite common to find "non-logical" urban nomads, or people who weren't parents but gave an answer for when they take child to hospital. i don't see a concious trend to exclude these type of surveys, nor a viable reason to assume they don't return. non-logicals can become really helpful because we can see when our questions or typographies don't make sense (i.e if we get a bunch of urban nomads, either our assumptions are wrong, or our questions are junk)

**Comment by lukechurch** [comment]
> @as2388 thanks, that makes sense
> 
> @lukechurch so it only comes in when we use split patterns for asking questions. I THINK it's just a fluke that this hasn't come up. But we often had a problem that for example we'd ask someone if they lived in an urban or rural areas, and then we'd only ask those in rural areas whether they were nomads (assumption = all nomads are rural dwellers) but because the split is not perfect in rapidpro (based on minimal regexs), it was quite common to find "non-logical" urban nomads, or people who weren't parents but gave an answer for when they take child to hospital. i don't see a concious trend to exclude these type of surveys, nor a viable reason to assume they don't return. non-logicals can become really helpful because we can see when our questions or typographies don't make sense (i.e if we get a bunch of urban nomads, either our assumptions are wrong, or our questions are junk)

Ok - can we use NIC (Not Internally Consistent) instead? NL could imply non-logiciality in a number of places that I think it's best for us to be explicit about.

**Comment by ParthaMoman** [comment]
NIC works for me!

**Comment by as2388** [comment]
(pushed NIC code, still waiting to be able to set inbound/outbound strings)

**Review by lukechurch — APPROVED** [review]

**Comment by as2388** [comment]
Received offline approval from @ParthaMoman; merging

**Pull request merged**
